version: "3.1"
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: record-db
    ports:
      - "5432:5432"
    volumes:
      - ./db/.tmp/db:/var/lib/postgresql/data
